const $=id=>document.getElementById(id),U="fm_user",F="fm_fac",C="fm_cur",R="fm_rec";
let s={user:null,facs:[],cur:null};function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function now(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function load(){try{s.user=JSON.parse(localStorage.getItem(U)||"null")}catch(e){}try{s.facs=JSON.parse(localStorage.getItem(F)||"[]")}catch(e){}try{s.cur=JSON.parse(localStorage.getItem(C)||"null")}catch(e){}s.facs=Array.isArray(s.facs)?s.facs:[]}
function save(){localStorage.setItem(U,JSON.stringify(s.user));localStorage.setItem(F,JSON.stringify(s.facs));localStorage.setItem(C,JSON.stringify(s.cur))}
function userUI(){if(!s.user)return;$("headUser").textContent=s.user.role?s.user.name+"（"+s.user.role+"）":s.user.name;$("setUser").value=s.user.name;$("userCard").classList.add("hidden");$("facCard").classList.remove("hidden");$("facListCard").classList.remove("hidden");renderFac()}
function renderFac(){$("facList").innerHTML=s.facs.length?s.facs.map(f=>'<div class="record"><div class="record-head"><div><b>'+esc(f.name)+'</b><div class="small">'+esc(f.no||"")+'</div></div><button class="btn" data-f="'+f.id+'">この施設で開始</button></div></div>').join(""):'<div class="hint">まだ登録されていません。</div>'}
$("saveUser").onclick=()=>{let n=$("userName").value.trim();if(!n)return alert("名前を入力してください");s.user={name:n,role:$("userRole").value.trim()};save();userUI()}
$("addFac").onclick=()=>{let n=$("facName").value.trim();if(!n)return alert("施設名を入力してください");let f={id:Date.now().toString(),name:n,no:$("facNo").value.trim()};s.facs.push(f);s.cur=f;save();activate(f);$("facName").value="";$("facNo").value=""}
$("facList").onclick=e=>{let b=e.target.closest("[data-f]");if(!b)return;let f=s.facs.find(x=>x.id===b.dataset.f);if(f){s.cur=f;save();activate(f)}}
function activate(f){s.cur=f;save();$("headFacility").textContent=f.name;$("setup").classList.add("hidden");$("app").classList.remove("hidden");$("footer").classList.remove("hidden");$("setFac").innerHTML=s.facs.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join("");$("setFac").value=f.id;newRecord()}
function build(){let root=$("checks"),last="";CHECKS.forEach((x,i)=>{if(x[0]!==last){root.insertAdjacentHTML("beforeend",'<div class="section">'+esc(x[0])+'</div>');last=x[0]}root.insertAdjacentHTML("beforeend",'<div class="item" data-i="'+i+'"><div class="item-title">'+esc(x[2])+'</div><div class="choice"><button class="btn ok" data-v="ok">異常なし</button><button class="btn ngb" data-v="ng">異常あり</button><button class="btn nab" data-v="na">対象外</button></div><div class="extra"><label>位置・状況</label><input class="loc"><label>コメント</label><textarea class="cm"></textarea></div></div>')})$("points").innerHTML=[1,2,3].map(n=>'<div class="item" data-p="'+n+'"><b>定点 '+n+'</b><label>健全度</label><select class="health"><option value="">未入力</option><option>S-5</option><option>S-4</option><option>S-3</option><option>S-2</option><option>S-1</option></select><button class="btn gps" style="width:100%;margin-top:8px">📍 現在位置を取得</button><div class="row2"><div><label>緯度</label><input class="lat"></div><div><label>経度</label><input class="lng"></div></div><label>写真</label><input type="file" accept="image/*" capture="environment"><label>コメント</label><textarea class="pc"></textarea><label>所見</label><textarea class="pf"></textarea></div>').join("");
$("checks").addEventListener("click",e=>{let b=e.target.closest(".choice .btn");if(!b)return;let it=b.closest(".item");it.querySelectorAll(".choice .btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");it.classList.toggle("ng",b.dataset.v==="ng");stats()});
$("points").addEventListener("click",e=>{let b=e.target.closest(".gps");if(!b)return;if(!navigator.geolocation)return alert("位置情報を取得できません");navigator.geolocation.getCurrentPosition(p=>{let it=b.parentElement;it.querySelector(".lat").value=p.coords.latitude.toFixed(6);it.querySelector(".lng").value=p.coords.longitude.toFixed(6);b.textContent="✅ 取得済み"},()=>alert("位置情報を取得できませんでした"));});$("points").addEventListener("change",stats)}
function stats(){let c=[...document.querySelectorAll("[data-i] .active")],ng=c.filter(x=>x.dataset.v==="ng").length;$("done").textContent=c.length;$("ngCount").textContent=ng;$("left").textContent=CHECKS.length-c.length;$("pdone").textContent=[...document.querySelectorAll(".health")].filter(x=>x.value).length}
function form(){let checks=[...document.querySelectorAll("[data-i]")].map(it=>{let i=+it.dataset.i,a=it.querySelector(".active");return{group:CHECKS[i][0],subgroup:CHECKS[i][1],item:CHECKS[i][2],status:a?.dataset.v||"",location:it.querySelector(".loc").value,comment:it.querySelector(".cm").value}}),points=[...document.querySelectorAll("[data-p]")].map(it=>({no:+it.dataset.p,health:it.querySelector(".health").value,lat:it.querySelector(".lat").value,lng:it.querySelector(".lng").value,comment:it.querySelector(".pc").value,finding:it.querySelector(".pf").value}));return{id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),facilityId:s.cur.id,facility:s.cur.name,user:s.user.name,inspectAt:$("inspectAt").value,prevAt:$("prevAt").value,importance:$("importance").value,facilityInfo:$("facilityInfo").value,address:$("address").value,finding:$("finding").value,special:$("special").value,checks,points,ng:checks.filter(x=>x.status==="ng").length,done:checks.filter(x=>x.status).length,savedAt:new Date().toISOString()}}
function recs(){try{return JSON.parse(localStorage.getItem(R)||"[]")}catch(e){return[]}}function put(a){localStorage.setItem(R,JSON.stringify(a))}
function newRecord(){document.querySelectorAll(".choice .btn").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".item").forEach(x=>x.classList.remove("ng"));document.querySelectorAll("input,textarea").forEach(x=>{if(!["userName","userRole","facName","facNo"].includes(x.id))x.value=""});document.querySelectorAll(".health").forEach(x=>x.value="");$("inspectAt").value=now();$("importance").value="S-5";stats()}
$("saveRecord").onclick=()=>{if(!s.cur)return alert("施設を選択してください");let r=form();if(!r.inspectAt)return alert("点検日時を入力してください");let a=recs();a.unshift(r);put(a);alert("記録を保存しました");newRecord();renderHist()}
$("saveBottom").onclick=()=>$("saveRecord").click();
function renderFilters(){let fs=$("filterFac");fs.innerHTML='<option value="">すべて</option>'+s.facs.map(f=>'<option>'+esc(f.name)+'</option>').join("");let ys=[...new Set(recs().map(r=>(r.inspectAt||"").slice(0,4)).filter(Boolean))].sort().reverse();$("filterYear").innerHTML='<option value="">すべて</option>'+ys.map(y=>'<option>'+y+'</option>').join("")}
function renderHist(){let a=recs(),ff=$("filterFac").value,fy=$("filterYear").value,fs=$("filterStatus").value;a=a.filter(r=>(!ff||r.facility===ff)&&(!fy||r.inspectAt.slice(0,4)===fy)&&(!fs||(fs==="ng"?r.ng>0:r.ng===0)));$("records").innerHTML=a.length?a.map(r=>'<div class="record"><div class="record-head"><div><b>'+esc(r.facility)+'</b><div class="small">'+esc((r.inspectAt||"").replace("T"," "))+'｜'+esc(r.user)+'</div></div><span class="badge '+(r.ng?"ng":"")+'">'+(r.ng?"異常 "+r.ng+"件":"異常なし")+'</span></div><div class="small" style="margin-top:6px">'+esc(r.finding||"所見なし")+'</div><button class="btn" data-del="'+r.id+'" style="margin-top:8px">削除</button></div>').join(""):'<div class="card hint">記録がありません。</div>';$("records").querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("削除しますか？")){put(recs().filter(r=>r.id!==b.dataset.del));renderHist()}})}
["filterFac","filterYear","filterStatus"].forEach(id=>$(id).onchange=renderHist)
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(t.dataset.v).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===t));if(t.dataset.v==="history"){renderFilters();renderHist()}if(t.dataset.v==="settings"){$("setUser").value=s.user.name;$("setFac").value=s.cur.id}})
$("setFac").onchange=()=>{let f=s.facs.find(x=>x.id===$("setFac").value);if(f){s.cur=f;save();$("headFacility").textContent=f.name}}
$("changeFac").onclick=()=>{let f=s.facs.find(x=>x.id===$("setFac").value);if(f){s.cur=f;save();$("headFacility").textContent=f.name;alert("切り替えました")}}
$("changeUser").onclick=()=>{let n=prompt("使用者名",s.user.name);if(n&&n.trim()){s.user.name=n.trim();save();userUI();$("headUser").textContent=s.user.name}}
$("switch").onclick=()=>{s.cur=null;save();$("setup").classList.remove("hidden");$("app").classList.add("hidden");$("footer").classList.add("hidden");userUI()}
function escCsv(v){return '"'+String(v??"").replaceAll('"','""')+'"'}
$("csvBtn").onclick=()=>{let a=recs(),h=["record_id","facility","user","inspect_at","prev_at","importance","ng","done","finding","special"];CHECKS.forEach((_,i)=>h.push("c"+String(i+1).padStart(2,"0")+"_status","c"+String(i+1).padStart(2,"0")+"_location","c"+String(i+1).padStart(2,"0")+"_comment"));for(let i=1;i<=3;i++)h.push("p"+i+"_health","p"+i+"_lat","p"+i+"_lng","p"+i+"_comment","p"+i+"_finding");let rows=[h];a.forEach(r=>{let v=[r.id,r.facility,r.user,r.inspectAt,r.prevAt,r.importance,r.ng,r.done,r.finding,r.special];r.checks.forEach(c=>v.push(c.status,c.location,c.comment));r.points.forEach(p=>v.push(p.health,p.lat,p.lng,p.comment,p.finding));rows.push(v)});let csv="﻿"+rows.map(r=>r.map(escCsv).join(",")).join("\r\n");dl("施設監視_PC取込.csv",csv,"text/csv;charset=utf-8")}
$("jsonBtn").onclick=()=>dl("施設監視バックアップ.json",JSON.stringify({version:1,user:s.user,facilities:s.facs,current:s.cur,records:recs()},null,2),"application/json")
$("jsonIn").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let p=JSON.parse(await f.text());if(p.user)s.user=p.user;if(Array.isArray(p.facilities))s.facs=p.facilities;if(p.current)s.cur=p.current;let m=new Map(recs().map(r=>[r.id,r]));(p.records||[]).forEach(r=>m.set(r.id,r));put([...m.values()]);save();userUI();if(s.cur)activate(s.cur);alert((p.records||[]).length+"件取り込みました")}catch(_){alert("読み込みできませんでした")}};
function dl(name,data,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function boot(){load();if(s.user){userUI();if(s.cur)activate(s.cur)}$("inspectAt").value=now()}
build();boot();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});